name = "kanji-english-blend"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

main = "./functions/[[path]].ts"

# Environment variables will be set in Cloudflare dashboard
[vars]
# DEEPSEEK_API_KEY = ""

[dev]
port = 8788

# Development environment
[env.development]
name = "kanji-english-blend-dev"

# Production environment
[env.production]
name = "kanji-english-blend"
