name = "kanji-english-blend"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Pages configuration
[site]
bucket = "dist"

[build]
command = "npm run build"

[[build.upload]]
format = "service-worker"

[functions]
directory = "functions"
node_compat = true

# Environment variables will be set in Cloudflare dashboard
[vars]
# DEEPSEEK_API_KEY = ""

# Development environment
[env.development]
name = "kanji-english-blend-dev"

# Production environment
[env.production]
name = "kanji-english-blend"
